allowBuilds:
  "@swc/core": true
  esbuild: true
  lefthook: true
minimumReleaseAgeExclude:
  - ras-stack-config@1.0.0
  - baseline-browser-mapping@2.11.13
  - browserslist@4.28.8
minimumReleaseAge: 10080
